### ISSUE TITLE
No rule to make 'ni-pkg'

### ISSUE THREAD

**Issue by sighaderi** [ni/linux#40]
Hi,
I want to build NI-Linux RT Kernel from source on NI-Linux RT 21.3
I did this steps : 
  git clone https://github.com/ni/linux.git
  cd linux
  git checkout nilrt/21.3/5.10
  export ARCH=x86_64
  sudo make nati_x86_64_defconfig
  sudo make ni-pkg

every step in OK, but when I run "sudo make ni-pkg", I get this error:
  UPD     include/config/kernel.release
  make[1]: *** No rule to make 'ni-pkg'.  Stop.
  make: *** [Makefile:1550: ni-pkg] Error 2

Thanks for any Hints

**Comment by awolpe** [comment]
I am having the same issue, and could also use some help with this. Thanks in advanced!

**Comment by shruthi-ravi** [comment]
Hello,

Unfortunately, our current instructions to build the kernel are outdated and no longer applicable to the x64-based System Image we ship in our more recent releases. We are in the process of updating our documentation, but in the meantime here's a new set of instructions that you can try out, assuming you have already set up the compiler toolchain.

### Compiling the Kernel
1. Set the kernel configuration to match NI’s settings.

    make nati_x86_64_defconfig

2. Compile the kernel.

    make -j<number_of_parallel_jobs> bzImage modules
    make modules_install INSTALL_MOD_PATH=<temporary_host_side_modules_location>

### Installing the Kernel
1. (optional) Backup /boot/runmode/bzImage on the target.

    cd /boot/runmode/
    mv bzImage bzImage-`uname -r`

2. Copy the new kernel to the target.

    scp arch/x86/boot/bzImage admin@<target>:/boot/runmode/
    cd <temporary_host_side_modules_location>
    tar cz lib | ssh admin@<target> tar xz -C /

3. Reboot the target.

    reboot

4. (optional) Check version of the updated kernel on the target.

    uname -a

### Rebuilding NI out-of-tree drivers
DKMS needs access to the kernel headers/config/source in order to
re-version out-of-tree NI drivers. You can copy the full kernel
source to the target and create the appropriate symlinks in
/lib/modules. But, this will not work very well on RT targets that
have limited disk space.

An alternative is to network mount the kernel source directory from
the host build machine.

1. Start the sshd daemon on the host.

    sudo systemctl start sshd

2. Install sshfs on the target.

    opkg update
    opkg install sshfs-fuse
    modprobe fuse

3. Mount the kernel source on the target.

    mkdir /usr/src/linux
    sshfs <user>@<host>:<path_to_kernel_source> /usr/src/linux

4. Fix dangling build and source symlinks.

    cd /lib/modules/`uname -r`/
    rm build source
    ln -s /usr/src/linux source
    ln -s source build

5. Prepare the tools needed for dkms.

    cd /lib/modules/`uname -r`/build
    make prepare
    make modules_prepare

6. Re-version the NI modules.

    dkms autoinstall

If you get strange gcc errors during this step, ensure that the gcc
version used to build the kernel on the host machine is compatible
with the gcc version on the target. Check the output logs under:
/var/lib/dkms/<ni_module>/<version>/build/make.log.

7. (optional) Check dkms status.

    dkms status

8. Reboot the target.

Hope this works well for you. Please let me know if you have any additional questions.

Thanks,
Shruthi

**Comment by sighaderi** [comment]
> 
> 
> Hello,
> 
> Unfortunately, our current instructions to build the kernel are outdated and no longer applicable to the x64-based System Image we ship in our more recent releases. We are in the process of updating our documentation, but in the meantime here's a new set of instructions that you can try out, assuming you have already set up the compiler toolchain.
> ### Compiling the Kernel
> 
>     1. Set the kernel configuration to match NI’s settings.
>        make nati_x86_64_defconfig
> 
>     2. Compile the kernel.
>        make -j<number_of_parallel_jobs> bzImage modules
>        make modules_install INSTALL_MOD_PATH=<temporary_host_side_modules_location>
> 
> 
> ### Installing the Kernel
> 
>     1. (optional) Backup /boot/runmode/bzImage on the target.
>        cd /boot/runmode/
>        mv bzImage bzImage-`uname -r`
> 
>     2. Copy the new kernel to the target.
>        scp arch/x86/boot/bzImage admin@:/boot/runmode/
>        cd <temporary_host_side_modules_location>
>        tar cz lib | ssh admin@ tar xz -C /
> 
>     3. Reboot the target.
>        reboot
> 
>     4. (optional) Check version of the updated kernel on the target.
>        uname -a
> 
> 
> ### Rebuilding NI out-of-tree drivers
> 
> DKMS needs access to the kernel headers/config/source in order to re-version out-of-tree NI drivers. You can copy the full kernel source to the target and create the appropriate symlinks in /lib/modules. But, this will not work very well on RT targets that have limited disk space.
> 
> An alternative is to network mount the kernel source directory from the host build machine.
> 
>     1. Start the sshd daemon on the host.
>        sudo systemctl start sshd
> 
>     2. Install sshfs on the target.
>        opkg update
>        opkg install sshfs-fuse
>        modprobe fuse
> 
>     3. Mount the kernel source on the target.
>        mkdir /usr/src/linux
>        sshfs @:<path_to_kernel_source> /usr/src/linux
> 
>     4. Fix dangling build and source symlinks.
>        cd /lib/modules/`uname -r`/
>        rm build source
>        ln -s /usr/src/linux source
>        ln -s source build
> 
>     5. Prepare the tools needed for dkms.
>        cd /lib/modules/`uname -r`/build
>        make prepare
>        make modules_prepare
> 
>     6. Re-version the NI modules.
>        dkms autoinstall
> 
> 
> If you get strange gcc errors during this step, ensure that the gcc version used to build the kernel on the host machine is compatible with the gcc version on the target. Check the output logs under: /var/lib/dkms/<ni_module>//build/make.log.
> 
>     1. (optional) Check dkms status.
>        dkms status
> 
>     2. Reboot the target.
> 
> 
> Hope this works well for you. Please let me know if you have any additional questions.
> 
> Thanks, Shruthi

Thank you very much for your help.

**Comment by awolpe** [comment]
Extremely helpful @shruthi-ravi ! Thank you very much!!!

**Comment by shruthi-ravi** [comment]
Hi all, I'm going to close this issue. If you have any further questions, please feel free to reopen this or open a new issue.
