### ISSUE TITLE
Update linux/scripts/package/buildnipkg script for 7AAE/Artemis/RoboRIO 2.0

### ISSUE THREAD

**Issue by marshallmassengill** [ni/linux#44]
This might just be me not knowing which branch to use but I couldn't find it anywhere with searching.  There is definitely a different boot script (via buildnipkg) for the RoboRIO 2.0 compared to the RoboRIO 1.0 that includes a few lines for booting from the SD Card correctly:

```
if test \${DeviceCode} -eq 0x7AAE; then
  setenv set_args 'setenv bootargs \${consoleparam} root=/dev/mmcblk0p3 rw \${usb_gadget_args} rcu_nocbs=all rootdelay=1 \$othbootargs'
else
  setenv set_args 'setenv bootargs \${consoleparam} \$mtdparts ubi.mtd=boot-config ubi.mtd=root root=ubi1:rootfs rw rootfstype=ubifs \${usb_gadget_args} rcu_nocbs=all \$othbootargs'
fi
```

Using the existing script with 'make ni-pkg' results in a build that won't boot on the RoboRIO 2.0 because it can't find the root.  At a minimum, the lines above seem to be missing from the file (along with some other bits).  At the very least it differs from the file in the current image being provided.  

I was able to extract the missing file and content from the image and inject the it into the buildnipkg script.  This enabled a custom kernel to boot correctly using branch nilrt/master/4.14.  I can submit a PR with all of those changes if that's desired but I didn't want to commit things that aren't meant to be public.  It would be awesome to have a kernel build process that works for the RoboRIO 2.0.

**Comment by gratian** [comment]
Yes, you are correct. This was an oversight that wasn't caught because 'make ni-pkg' is only used for manual kernel builds on 4.14 or earlier branches. Newer 5.x branches do not use ni-pkg anymore and only support x86_64 targets (so far).

nilrt/master/4.14 is the correct branch for Zynq/ARM based targets like RoboRIO 2.0 and current releases.

PRs are very much appreciated. Fair warning replies might be slow over the next couple of weeks due to holidays/vacation.

**Comment by marshallmassengill** [comment]
Thanks!  https://github.com/ni/linux/pull/47 submitted.  No major rush and happy holidays!
