### ISSUE TITLE
:enhancement: Docer image for testing purporsses 

### ISSUE THREAD

**Issue by ansible42** [ni/linux#80]
Including a docker image in the official pipeline would be helpful so that we can use that image for testing in our own CI workflows.

**Comment by amstewart** [comment]
Hey @ansible42. Coincidentally, we were just discussing this internally. :)

Could you open an issue on the [ni/nilrt.git](https://github.com/ni/nilrt/issues) repo? That's the top-level of the NI LinuxRT project, and is were we would like to track requests like this.

I'd be interested to understand more about your requirements, so that I can feed that into our backlog - but we can have that discussion on the new issue.

**Comment by ansible42** [comment]
I'll shoot you an email as some info is not public.

**Comment by bstreiff** [comment]
Closing this issue in favor of https://github.com/ni/nilrt/issues/175 since it's not kernel-related.
